DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;


CREATE TABLE log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  level TEXT NOT NULL,
  message TEXT NOT NULL
);

CREATE TABLE cloud_ptr (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  ingest TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  list_clouds BLOB NOT NULL
)