@version: 4.6
@module system-source

options { 
  use-uniqid(yes);
  suppress(10);
};

source s_systemd {
  system();
};

destination pipelog {
  file(
    "/data/cache/syslog-ng/messages.log" 
    owner("root") 
    group("root") 
    perm(0640) 
    fsync(yes)
    flush-lines(10)
    create_dirs(yes)
    );
};

log {
  source(s_systemd);
  destination(pipelog);
};
