require conf/machine/raspberrypi3-64.conf

RPI_KERNEL_DEVICETREE_OVERLAYS:remove = " \
    overlays/disable-bt.dtbo \
    overlays/disable-wifi.dtbo \
"

KBUILD_DEFCONFIG:raspberrypi3-64-robot = "bcmrpi3_defconfig"